github.com:
    users:
        bilbywilby:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: bilbywilby
