github.com:
    users:
        bilbywilby:
            oauth_token: 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
    git_protocol: ssh
    user: bilbywilby
    oauth_token: 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
